### GET all users
# @name Get All Users
GET localhost:3000/api/users

### Create new user
# @name Create new user
POST localhost:3000/api/users
Content-Type: application/json

{
  "username": "gg",
  "name": "greg grog",
  "password": "12345"
}


### Get all blogs
# @name Get All Blogs
GET localhost:3000/api/blogs

### Creates a new blog
# @name Create new blog
POST  localhost:3000/api/blogs
Content-Type: application/json

{
  "title": "mingling",
  "author": "greg",
  "url": "/api/blogs",
  "likes": 3,
  "userId": "674eba22ef2cc7f30a10a353"
}